# Generated by Django 5.1.4 on 2025-04-20 02:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_level', models.IntegerField()),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('updated_by', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_voter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('BALIK_PCS', 'BALIK_PCS'), ('RENEWED', 'RENEWED'), ('RE_MEMBER', 'RE_MEMBER'), ('CURRENT_BOT', 'CURRENT_BOT')], default='NEW', max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_paid_billed', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partner_or_individual', models.CharField(blank=True, max_length=50, null=True)),
                ('month_year_entered', models.CharField(blank=True, max_length=7, null=True)),
                ('anniversary_month', models.CharField(blank=True, max_length=3, null=True)),
                ('title', models.CharField(max_length=20)),
                ('member', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('allow_proxy', models.BooleanField(default=False)),
                ('requested_proxy', models.JSONField(blank=True, default=list)),
                ('received_proxy_requests', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
