# Generated by Django 5.1.4 on 2025-04-20 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='anniversary_month',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_paid_billed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_voter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='member',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='month_year_entered',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='partner_or_individual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='record_status_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_by',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voted_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voted_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
