# Generated by Django 5.1.4 on 2025-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_allow_proxy_customuser_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('BALIK_PCS', 'BALIK_PCS'), ('RENEWED', 'RENEWED'), ('RE_MEMBER', 'RE_MEMBER'), ('CURRENT_BOT', 'CURRENT_BOT')], default='NEW', max_length=20),
        ),
    ]
