# Generated by Django 5.1.4 on 2025-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proxy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
