# Generated by Django 5.1.4 on 2025-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_accepted_customuser_proxy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
