# Generated by Django 5.1.4 on 2025-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('voter', 'Voter'), ('elecom', 'Elecom')], default='voter', max_length=10),
        ),
    ]
