# Generated by Django 5.1.4 on 2025-04-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='national_id',
        ),
    ]
