# Generated by Django 5.2 on 2025-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('election_title', models.CharField(max_length=255)),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('num_ballots', models.PositiveIntegerField()),
            ],
        ),
    ]
