# Generated by Django 5.2 on 2025-04-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
