# Generated by Django 5.2 on 2025-04-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_candidate_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('role_level', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='role_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.role'),
            preserve_default=False,
        ),
    ]
