# Generated by Django 5.2 on 2025-04-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_role_remove_candidate_role_id_candidate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
