# Generated by Django 5.2 on 2025-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_alter_candidate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
            ],
        ),
    ]
