# Generated by Django 5.2 on 2025-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_committee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='election_title',
            new_name='election_name',
        ),
        migrations.AddField(
            model_name='election',
            name='no_ballots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='election',
            name='no_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='election',
            name='poll_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='poll_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='num_ballots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
