# Generated by Django 5.2 on 2025-04-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_rename_election_title_election_election_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='num_ballots',
        ),
    ]
