# Generated by Django 5.2 on 2025-04-20 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_remove_election_num_ballots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='poll_closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='poll_open_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
