# Generated by Django 5.2 on 2025-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_alter_election_poll_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='poll_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='poll_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_start',
            field=models.DateTimeField(),
        ),
    ]
