# Generated by Django 5.2 on 2025-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='proxy_for_voter_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
